wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.20
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737282631.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.20
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
delta_foot_mass:
  desc: null
  value: '0'
delta_leg_mass:
  desc: null
  value: '0'
delta_thigh_mass:
  desc: null
  value: '0.35'
