wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.20
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737046203.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.20
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
clip_range:
  desc: null
  value: 0.30429795037392454
ent_coef:
  desc: null
  value: 0.016878062758126113
learning_rate:
  desc: null
  value: 0.0001321985541917881
