_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
clip_range:
    value: 0.34137166553574877
ent_coef:
    value: 0.018800320168821542
learning_rate:
    value: 0.0005942579139567411
